---
title: My coding journal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: rathod.vivek at gmail.com
description: Intended to be a place where I can capture coding and programming knowledge.
  It is mostly focused on .NET and C# with some work related to databases and security
  as well.
baseurl: ''
url: https://vivekrathod.com
twitter_username: vrthd
github_username: vivekrathod
theme: minima
plugins:
- jekyll-feed
disqus:
  shortname: utteranc.es
